[[one-time-token-login]]
= One-Time Token Login

Spring Security offers support for One-Time Token (OTT) authentication via the `oneTimeTokenLogin()` DSL.
Before diving into implementation details, it's important to clarify the scope of the OTT feature within the framework, highlighting what is supported and what isn't.

== Understanding One-Time Tokens vs. One-Time Passwords

It's common to confuse One-Time Tokens (OTT) with https://en.wikipedia.org/wiki/One-time_password[One-Time Passwords] (OTP), but in Spring Security, these concepts differ in several key ways.
For clarity, we'll assume OTP refers to https://en.wikipedia.org/wiki/Time-based_one-time_password[TOTP] (Time-Based One-Time Password) or https://en.wikipedia.org/wiki/HMAC-based_one-time_password[HOTP] (HMAC-Based One-Time Password).

=== Setup Requirements

- OTT: No initial setup is required. The user doesn't need to configure anything in advance.
- OTP: Typically requires setup, such as generating and sharing a secret key with an external tool to produce the one-time passwords.

=== Token Delivery

- OTT: The `oneTimeTokenLogin()` feature needs a javadoc:org.springframework.security.authentication.ott.OneTimeTokenSender[] bean, responsible for delivering the token to the end user.
- OTP: The token is generated by an external tool, so there's no need to send it to the user via the application.

=== Token Generation

- OTT: The javadoc:org.springframework.security.authentication.ott.OneTimeTokenService#generate(org.springframework.security.authentication.ott.OneTimeTokenAuthenticationRequest)[] method requires a javadoc:org.springframework.security.authentication.ott.OneTimeToken[] to be returned, emphasizing server-side generation.
- OTP: The token is not necessarily generated on the server side, it's often created by the client using the shared secret.

In summary, One-Time Tokens (OTT) provide a way to authenticate users without additional account setup, differentiating them from One-Time Passwords (OTP), which typically involve a more complex setup process and rely on external tools for token generation.

The One-Time Token Login works in two major steps.

1. User request a token by submitting their user identifier, usually the username, and the token is delivered to them, via e-mail, SMS, Magic Link, etc.
2. User submits the token to the application and, if valid, the user gets logged in.

[[default-pages]]
== Default Login Page and Default One-Time Token Submit Page

The `oneTimeTokenLogin()` DSL can be used in conjunction with `formLogin()`, which will produce an additional One-Time Token Request Form in the xref:servlet/authentication/passwords/form.adoc[default generated login page].
It will also set up the javadoc:org.springframework.security.web.authentication.ui.DefaultOneTimeTokenSubmitPageGeneratingFilter[] to generate a default One-Time Token submit page.

In the following sections we will explore how to configure OTT Login for your needs.

- <<sending-token-to-user,Sending the token to the user>>
- <<configuring-ott-submit-page,Configuring the One-Time Token submit page>>
- <<changing-authentication-request-url,Changing the authentication request URL>>

[[sending-token-to-user]]
== Sending the Token to the User

As we mentioned before, the `oneTimeTokenLogin()` requires a bean of type javadoc:org.springframework.security.authentication.ott.OneTimeTokenSender[] because Spring Security cannot decide the best strategy to deliver the tokens to your users.
Some of the most common delivery strategies are: SMS, Token via E-mail, Magic Link via E-mail, and others.
In the following example, we are going to create a magic link and sent it to the user's email.

.One-Time Token Login Configuration
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) {
        http
            // ...
            .formLogin(Customizer.withDefaults())
            .oneTimeTokenLogin(Customizer.withDefaults());
        return http.build();
    }

}

import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;

@Component <1>
public class MagicLinkOneTimeTokenSender implements OneTimeTokenSender {

    private final JavaMailSender mailSender;

    // constructor omitted

    @Override
    public void send(OneTimeToken oneTimeToken) {
        String magicLink = "http://localhost:8080/login/ott?token=" + oneTimeToken.getToken(); <2>
        String userEmail = getUserEmail(oneTimeToken.getUsername()); <3>
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom("noreply@example.com");
        message.setTo(userEmail);
        message.setSubject("Your Spring Security One Time Token");
        message.setText("Use the following link to sign in into the application: " + magicLink);
        this.mailSender.send(message); <4>
    }

    private String getUserEmail(String username) {
        // ...
    }

}

----
======

<1> Make the `MagicLinkOneTimeTokenSender` a Spring Bean so it is automatically picked up by `oneTimeTokenLogin()` DSL
<2> Create a login processing URL with the `token` as a query param
<3> Retrieve the user's email based on the username
<4> Use the `JavaMailSender` API to send the email to the user with the magic link

The email content will look similar to:

> Use the following link to sign in into the application: \http://localhost:8080/login/ott?token=a830c444-29d8-4d98-9b46-6aba7b22fe5b

The default submit page will detect that the URL has the `token` query param and will automatically submit the form with the token value, effectively logging the user into the application.

[[changing-authentication-request-url]]
== Changing the Authentication Request URL

By default, the javadoc:org.springframework.security.web.authentication.ott.OneTimeTokenAuthenticationRequestFilter[] listens to `POST /ott/authenticate` requests.
That URL can be changed by using the `authenticationRequestUrl(String)` DSL method:

.Changing the Authentication Request URL
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) {
        http
            // ...
            .formLogin(Customizer.withDefaults())
            .oneTimeTokenLogin((ott) -> ott
                .authenticationRequestUrl("/ott/myauthenticationrequesturl")
            );
        return http.build();
    }

}
----
======

== Changing the Redirect URL After a Successful Authentication Request

After a successful authentication request, where the token has been generated and delivered, the user-agent is redirected to `/login/ott`.
The redirect URL can be changed by using the `authenticationRequestRedirectUrl(String)` DSL method:

.Changing the Authentication Request Redirect URL
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) {
        http
            // ...
            .formLogin(Customizer.withDefaults())
            .oneTimeTokenLogin((ott) -> ott
                .authenticationRequestRedirectUrl("/ott/submit")
            );
        return http.build();
    }

}
----
======

If you are using the default submit page, you should also <<changing-submit-page-url,configure it to the same URL that you are using as a redirect>>.

[[changing-submit-page-url]]
== Changing the Default Submit Page URL

The default One-Time Token submit page is generated by the javadoc:org.springframework.security.web.authentication.ui.DefaultOneTimeTokenSubmitPageGeneratingFilter[] and listens to `GET /login/ott`.
The URL can also be changed, like so:

.Configuring the Default Submit Page URL
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) {
        http
            // ...
            .formLogin(Customizer.withDefaults())
            .oneTimeTokenLogin((ott) -> ott
                .submitPageUrl("/ott/submit")
            );
        return http.build();
    }

}
----
======

[[disabling-default-submit-page]]
== Disabling the Default Submit Page

If you want to use your own One-Time Token submit page, you can disable the default page and then provide your own endpoint.

.Disabling the Default Submit Page
[tabs]
======
Java::
+
[source,java,role="primary"]
----
@Configuration
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) {
        http
            // ...
            .formLogin(Customizer.withDefaults())
            .oneTimeTokenLogin((ott) -> ott
                .showSubmitPage(false)
            );
        return http.build();
    }

}

@Controller
public class MyController {

    @GetMapping("/my-ott-submit")
    public String ottSubmitPage() {
        return "my-ott-submit";
    }

}
----
======
